version: "3"

services:
        chad_ws:
                build: "."
                image: "zxgio/chad_ws"
                container_name: "chad_ws"
                env_file: "web_variables.env"
                ports:
                  - "0.0.0.0:8000:5000"
                volumes:
                  - "./wg_certificates:/wg_certificates:ro"
                restart: "unless-stopped"
